Repository passgodev/passgo, pull requests merged in 2025-05, with the labels that each got.

#41 Pdf ticket
  pom.xml
  src/main/java/pl/uj/passgo/services/PDFGenerator.java
  src/main/resources/passgo.png
Labels: bug

#42 Admin controller
  src/main/java/pl/uj/passgo/controllers/member/MemberController.java
  src/main/java/pl/uj/passgo/converters/StringToMemberTypeConverter.java
  src/main/java/pl/uj/passgo/exception/handlers/EventExceptionHandler.java
  src/main/java/pl/uj/passgo/exception/handlers/ExceptionMessageResponse.java
  src/main/java/pl/uj/passgo/mappers/client/ClientMapper.java
  src/main/java/pl/uj/passgo/mappers/member/MemberMapper.java
  src/main/java/pl/uj/passgo/mappers/member/MemberResponseMapper.java
  src/main/java/pl/uj/passgo/mappers/organizer/OrganizerMapper.java
  src/main/java/pl/uj/passgo/models/DTOs/member/ClientDto.java
  src/main/java/pl/uj/passgo/models/DTOs/member/OrganizerDto.java
  src/main/java/pl/uj/passgo/models/DTOs/ticket/TicketDto.java
  src/main/java/pl/uj/passgo/models/DTOs/transaction/TransactionDto.java
  src/main/java/pl/uj/passgo/models/member/Member.java
  src/main/java/pl/uj/passgo/models/member/MemberCredential.java
  src/main/java/pl/uj/passgo/models/responses/member/ClientMemberResponse.java
  src/main/java/pl/uj/passgo/models/responses/member/MemberResponse.java
  src/main/java/pl/uj/passgo/models/responses/member/OrganizerMemberResponse.java
  src/main/java/pl/uj/passgo/resolvers/authentication/WebConfig.java
  src/main/java/pl/uj/passgo/services/authentication/AuthenticationService.java
  src/main/java/pl/uj/passgo/services/member/MemberService.java
  src/main/resources/db/migration/V1.5.1__moved_isActive_attribute.sql
Labels: enhancement

#44 feat(elk): added elk stack
  .gitignore
  README.md
  elk/docker-compose.yml
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/logstash.conf
  pom.xml
  src/main/resources/logback-spring.xml
Labels: enhancement

#46 fix(ticket): fixed ticket, customer relationship with multiplicity
  src/main/java/pl/uj/passgo/models/Ticket.java
  src/main/resources/db/migration/V1.7.1__ticket_client_relation_multiplicity.sql
Labels: bug

#47 feat(memberTypeJwt): added memberType claim to jwt login response
  src/main/java/pl/uj/passgo/configuration/security/jwt/JwtService.java
Labels: enhancement

#53 get member by id
  src/main/java/pl/uj/passgo/configuration/security/jwt/JwtService.java
  src/main/java/pl/uj/passgo/controllers/member/MemberController.java
  src/main/java/pl/uj/passgo/exception/MemberCredentialNotFoundException.java
  src/main/java/pl/uj/passgo/exception/handlers/EventExceptionHandler.java
  src/main/java/pl/uj/passgo/models/responses/member/ClientMemberResponse.java
  src/main/java/pl/uj/passgo/models/responses/member/OrganizerMemberResponse.java
  src/main/java/pl/uj/passgo/repos/member/OrganizerRepository.java
  src/main/java/pl/uj/passgo/services/LoggedInMemberContextService.java
  src/main/java/pl/uj/passgo/services/member/MemberService.java
Labels: enhancement

#57 Auth logout
  src/main/java/pl/uj/passgo/configuration/security/jwt/JwtAuthenticationConfiguration.java
  src/main/java/pl/uj/passgo/controllers/authentication/AuthenticationController.java
  src/main/java/pl/uj/passgo/models/DTOs/authentication/logout/LogoutRequest.java
  src/main/java/pl/uj/passgo/services/authentication/AuthenticationService.java
  src/main/java/pl/uj/passgo/services/authentication/RefreshTokenService.java
Labels: enhancement

#63 Weather api
  src/main/java/pl/uj/passgo/configuration/security/RestTemplateConfiguration.java
  src/main/java/pl/uj/passgo/controllers/EventController.java
  src/main/java/pl/uj/passgo/exception/weather/EventWeatherException.java
  src/main/java/pl/uj/passgo/models/DTOs/weahter/EventWeatherRequest.java
  src/main/java/pl/uj/passgo/models/DTOs/weahter/EventWeatherResponse.java
  src/main/java/pl/uj/passgo/services/EventService.java
  src/main/java/pl/uj/passgo/services/weather/EventWeatherService.java
  src/main/java/pl/uj/passgo/services/weather/WeatherService.java
Labels: enhancement

#68 Workflow refactor
  .github/workflows/build_upload.yml
  .github/workflows/demo.yml
  .github/workflows/snyk_check.yml
Labels: refactor
